services:
#  pgvector:
#    image: pgvector/pgvector:pg16
#    ports:
#      - 5432:5432
#    profiles:
#      - pgvector
#    restart: always
#    environment:
#      PGUSER: ${PGVECTOR_PGUSER:-postgres}
#      POSTGRES_PASSWORD: ${PGVECTOR_POSTGRES_PASSWORD:-postgres1234}
#      POSTGRES_DB: ${PGVECTOR_POSTGRES_DB:-postgres}
#      PGDATA: ${PGVECTOR_PGDATA:-/var/lib/postgresql/data/pgdata}
#    volumes:
#      - ./volumes/pgvector/data:/var/lib/postgresql/data
#    healthcheck:
#      test: [ "CMD", "pg_isready" ]
#      interval: 1s
#      timeout: 3s
#      retries: 30


  postgresml:
    image: ghcr.io/postgresml/postgresml:2.9.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
    volumes:
      - postgresml_data:/var/lib/postgresql
    ports:
      - "5433:5432"
    command: bash -c "sudo -u postgresml psql -d postgresml"

volumes:
  postgresml_data:
